#!/bin/bash

GenieChoice=1
ROTATIONS=100
SECTORS=1
DELTAPHI=0
THETAEL_LB=40
THETAEL_UB=45
MOMEL_LB=0
PROTSECTORS=0
PROT_DELTAPHI=0
THETAPROT_LB=0
THETAPROT_UB=180
MOMPROT_LB=0
MOMPROT_UB=0

Energy=2261

./genie_analysis C12 $Energy $GenieChoice $ROTATIONS $SECTORS $DELTAPHI $THETAEL_LB $THETAEL_UB $MOMEL_LB $PROTSECTORS $PROT_DELTAPHI $THETAPROT_LB $THETAPROT_UB $MOMPROT_LB $MOMPROT_UB
